tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

tap "borkdude/brew"
tap "choria-io/tap"
tap "d12frosted/emacs-plus"
tap "dagger/tap"
tap "hashicorp/tap"
tap "pulumi/tap"


brew "age"
brew "aspell"
brew "automake"
brew "awscli"
brew "babashka"
brew "bat"
brew "boot-clj"
brew "choria-io/tap/appbuilder"
brew "clj-kondo"
brew "clojure-lsp"
brew "colima"
brew "conftest"
brew "dagger/tap/dagger"
brew "delve"
brew "deno"
brew "dog"
brew "emacs-plus", args: ["with-elrumo1-icon", "with-native-comp"]
brew "entr"
brew "exa"
brew "fd"
brew "gh"
brew "git"
brew "git-delta"
brew "go"
brew "gopls"
brew "gradle"
brew "hashicorp/tap/terraform"
brew "hunspell"
brew "isync"
brew "jdtls"
brew "jq"
brew "just"
brew "kubectl"
brew "leiningen"
brew "mage"
brew "make"
brew "mas"
brew "meson"
brew "mg"
brew "mu"
brew "neovim"
brew "nodejs"
brew "opa"
brew "openssh"
brew "podman"
brew "pulumi/tap/pulumi"
brew "pwgen"
brew "python"
brew "ripgrep"
brew "rust-analyzer"
brew "rustup-init"
brew "shellcheck"
brew "signify-osx"
brew "sk"
brew "starship"
brew "tealdeer"
brew "terraform-ls"
brew "tmux"
brew "tokei"
brew "weechat"
brew "wget"
brew "yarn"
brew "zoxide"


cask "1password"
cask "1password-cli"
cask "alacritty"
cask "alfred"
cask "beekeeper-studio"
cask "bettertouchtool"
cask "dash"
cask "docker"
cask "element"
cask "firefox"
cask "font-et-book"
cask "font-fira-mono-nerd-font"
cask "font-linux-libertine"
cask "font-profont-nerd-font"
cask "gpg-suite"
cask "iterm2"
cask "jetbrains-toolbox"
cask "ksdiff"
cask "little-snitch"
cask "miniconda"
cask "pgadmin4"
cask "postgres-unofficial"
cask "raindropio"
cask "rectangle-pro"
cask "signal"
cask "spotify"
cask "steam"
cask "temurin"
cask "thingsmacsandboxhelper"
cask "transmission"
cask "visual-studio-code"


mas "Bear", id: 1091189122
mas "Day One", id: 1055511498
mas "Deliveries", id: 290986013
mas "DuckDuckGo Privacy Essentials", id: 1482920575
mas "Kaleidoscope", id: 1575557335
mas "Keynote", id: 409183694
mas "Marked 2", id: 890031187
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Paprika", id: 1303222628
mas "Pixelmator Pro", id: 1289583905
mas "Poolside FM", id: 1514817810
mas "Reeder 5", id: 1529448980
mas "Save to Pocket", id: 1477385213
mas "Save to Raindrop.io", id: 1549370672
mas "Silicio", id: 933627574
mas "Theine", id: 955848755
mas "Things 3", id: 904280696
mas "Transmit 5", id: 1436522307
mas "Twitter", id: 1482454543
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
